[theme]
base="dark"

primaryColor = "#d0f1f5"
linkColor = "#c4eff2"
# Culoarea principalÄƒ a textului
# Codul hex pentru "darkGoldenrod"
textColor = "#7af2ff"
borderColor = "#c4eff2"
showWidgetBorder=true
font = "Poppins"

#
##[theme2]
#base2 = "light"
#primaryColor2 = "#d4cba5"
#linkColor2 = "#807a63"
#textColor2 = "#a69f81"
#font2 = "Poppins"
#showWidgetBorder2 = true

